[[default-session]]
name = "Bacon"

[[session]]
name = "Installer"
path = "~/repos/installer"
startup_command = "nvim ."

[[session]]
name = "PDF-Service"
path = "~/repos/pdf-service"
startup_command = "nvim ."

[[session]]
name = "API-Gateway"
path = "~/repos/api-gateway"
startup_command = "nvim ."

[[session]]
name = "Device-Export"
path = "~/repos/device-export"
startup_command = "nvim ."

[[session]]
name = "Studio"
path = "~/repos/dt-studio-frontend"
startup_command = "nvim ."

[[session]]
name = "Dotfiles"
path = "~/.dotfiles"
startup_command = "nvim ."

